version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-bingo
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbzinhas2
      POSTGRES_DB: bingo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: bingo-api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:dbzinhas2@db:5432/bingo

volumes:
  postgres-data:
